//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CobolStudio.Main.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CobolStudio.Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on &quot;Add&quot; button.
        /// </summary>
        internal static string Add_The_File_Message {
            get {
                return ResourceManager.GetString("Add_The_File_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        internal static string Add_The_File_Title {
            get {
                return ResourceManager.GetString("Add_The_File_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name already exists..
        /// </summary>
        internal static string Already_Exists_Message {
            get {
                return ResourceManager.GetString("Already_Exists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate File Name.
        /// </summary>
        internal static string Already_Exists_Title {
            get {
                return ResourceManager.GetString("Already_Exists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name Already Added.
        /// </summary>
        internal static string Area_Already_Exists_Message {
            get {
                return ResourceManager.GetString("Area_Already_Exists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Area Name.
        /// </summary>
        internal static string Area_Already_Exists_Title {
            get {
                return ResourceManager.GetString("Area_Already_Exists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code has been generated, please check your directory..
        /// </summary>
        internal static string Code_Generation_Message {
            get {
                return ResourceManager.GetString("Code_Generation_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Generated.
        /// </summary>
        internal static string Code_Generation_Message_Title {
            get {
                return ResourceManager.GetString("Code_Generation_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 20 database records are allowed.
        /// </summary>
        internal static string DB_Rec_Limit_Message {
            get {
                return ResourceManager.GetString("DB_Rec_Limit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Record Limit Exceed.
        /// </summary>
        internal static string DB_Rec_Limit_Message_Title {
            get {
                return ResourceManager.GetString("DB_Rec_Limit_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DB Record Already Added.
        /// </summary>
        internal static string DBRec_Already_Exists_Message {
            get {
                return ResourceManager.GetString("DBRec_Already_Exists_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate DB Record.
        /// </summary>
        internal static string DBRec_Already_Exists_Title {
            get {
                return ResourceManager.GetString("DBRec_Already_Exists_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Area name to add.
        /// </summary>
        internal static string Enter_AreaName_Message {
            get {
                return ResourceManager.GetString("Enter_AreaName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area Name Field Empty.
        /// </summary>
        internal static string Enter_AreaName_Title {
            get {
                return ResourceManager.GetString("Enter_AreaName_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a copybook name to add.
        /// </summary>
        internal static string Enter_CopyBook_Message {
            get {
                return ResourceManager.GetString("Enter_CopyBook_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CopyBook Field Empty.
        /// </summary>
        internal static string Enter_CopyBook_Title {
            get {
                return ResourceManager.GetString("Enter_CopyBook_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Database record name to add.
        /// </summary>
        internal static string Enter_DBRec_Message {
            get {
                return ResourceManager.GetString("Enter_DBRec_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DBRec Field Empty.
        /// </summary>
        internal static string Enter_DBRec_Title {
            get {
                return ResourceManager.GetString("Enter_DBRec_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the following..
        /// </summary>
        internal static string Error_Message_Header {
            get {
                return ResourceManager.GetString("Error_Message_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string Export_Button_Text {
            get {
                return ResourceManager.GetString("Export_Button_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 10 files are allowed.
        /// </summary>
        internal static string File_Limit_Message {
            get {
                return ResourceManager.GetString("File_Limit_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Limit Exceed.
        /// </summary>
        internal static string File_Limit_Message_Title {
            get {
                return ResourceManager.GetString("File_Limit_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name Empty.
        /// </summary>
        internal static string File_Name_Empty_Title {
            get {
                return ResourceManager.GetString("File_Name_Empty_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a file name.
        /// </summary>
        internal static string File_Name_Filed_Empty_Message {
            get {
                return ResourceManager.GetString("File_Name_Filed_Empty_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap negative_sign {
            get {
                object obj = ResourceManager.GetObject("negative_sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New copybook name entered, this will be added to the copybook list.
        /// </summary>
        internal static string New_CopyBook_Message {
            get {
                return ResourceManager.GetString("New_CopyBook_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Copybook.
        /// </summary>
        internal static string New_CopyBook_Title {
            get {
                return ResourceManager.GetString("New_CopyBook_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Database Area entered, this will be added to the DB Area list.
        /// </summary>
        internal static string New_DatabaseArea_Message {
            get {
                return ResourceManager.GetString("New_DatabaseArea_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Database Area.
        /// </summary>
        internal static string New_DatabaseArea_Title {
            get {
                return ResourceManager.GetString("New_DatabaseArea_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Database Record entered, this will be added to the DB Record list.
        /// </summary>
        internal static string New_DatabaseRecord_Message {
            get {
                return ResourceManager.GetString("New_DatabaseRecord_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Database Record.
        /// </summary>
        internal static string New_DatabaseRecord_Title {
            get {
                return ResourceManager.GetString("New_DatabaseRecord_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New SubSchema added.
        /// </summary>
        internal static string New_Schema_Title {
            get {
                return ResourceManager.GetString("New_Schema_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Subschema name entered, this will be added to the Subschema list.
        /// </summary>
        internal static string New_Subschema_Message {
            get {
                return ResourceManager.GetString("New_Subschema_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Subschema.
        /// </summary>
        internal static string New_Subschema_Title {
            get {
                return ResourceManager.GetString("New_Subschema_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a row.
        /// </summary>
        internal static string No_Row_Selected_Message {
            get {
                return ResourceManager.GetString("No_Row_Selected_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Row selected.
        /// </summary>
        internal static string No_Row_Selected_Title {
            get {
                return ResourceManager.GetString("No_Row_Selected_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Schema Entered for given Database/Area.
        /// </summary>
        internal static string No_Schema_Message {
            get {
                return ResourceManager.GetString("No_Schema_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema Name Empty.
        /// </summary>
        internal static string No_Schema_Title {
            get {
                return ResourceManager.GetString("No_Schema_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Plus_sign {
            get {
                object obj = ResourceManager.GetObject("Plus_sign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops! System error. Please contact administrator..
        /// </summary>
        internal static string System_Error_Message {
            get {
                return ResourceManager.GetString("System_Error_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - Message.
        /// </summary>
        internal static string System_Error_Message_Title {
            get {
                return ResourceManager.GetString("System_Error_Message_Title", resourceCulture);
            }
        }
    }
}
